BW-143: Add QA package and prepare for Drupal 9
digipolisgent/drupal_module_dg-cookiebot pull request #6
Opened 2020-12-10 13:15 UTC by matthijs-va

2020-12-14 07:13 UTC, zero2one requested changes, later dismissed

2020-12-14 07:13 UTC, zero2one commented on .travis.yml
> +    - php: 7.4
Can be removed since it doesn't fail ;-)

2020-12-29 08:01 UTC, MPParsley commented on .travis.yml
> +    - php: 7.4
```suggestion
```

2020-12-29 08:44 UTC, MPParsley commented on .travis.yml
> +    -Dsonar.tests=tests
```suggestion
    -Dsonar.tests=tests
    -Dsonar.exclusions=**/tests/**/*
```

2020-12-29 10:16 UTC, MPParsley approved these changes

2020-12-29 14:16 UTC, MPParsley approved these changes

2020-12-30 13:06 UTC, MPParsley approved these changes

2020-12-30 13:27 UTC, merged